---
# Setup a Docker node

- include: redhat.yml
  when: ansible_distribution == 'RedHat'

- name: docker | setup repository
  become: yes
  get_url:
    dest: /etc/yum.repos.d/docker-ce.repo
    url: https://download.docker.com/linux/centos/docker-ce.repo

- name: docker | install docker
  become: yes
  yum:
    pkg: "docker-ce{{ (docker_version | length > 0) | ternary('-' + docker_version, '') }}"
    state: present

- name: docker | setup lvm docker-pool
  become: yes
  lvol:
    vg: "{{ docker_vgname }}"
    lv: docker-pool
    size: "{{ docker_poolsize }}"
    opts: "{{ docker_lvopts | default(None) }} --thin --poolmetadatasize {{ docker_metadatasize }}"
  when: docker_use_custom_storage

- name: docker | configuration directory
  become: yes
  file:
    path: /etc/docker
    state: directory

# https://docs.docker.com/engine/reference/commandline/dockerd/#linux-configuration-file
- name: docker | configure docker options
  become: yes
  template:
    src: etc-docker-daemon-json.j2
    dest: /etc/docker/daemon.json
    backup: yes
  notify:
    - restart docker

- name: docker | enable
  become: yes
  service:
    name: docker
    state: started
    enabled: yes
  when: docker_systemd_setup

- name: docker | group members
  become: yes
  user:
    name: "{{ item }}"
    groups: docker
    append: yes
  with_items: "{{ docker_groupmembers }}"
